spring.application.name=padmasiniAdmin_1

# MongoDB connection
spring.data.mongodb.uri=mongodb+srv://swaminathan:Padmasini%4004@subjects.sqqcggz.mongodb.net/subjects?retryWrites=true&w=majority&appName=Subjects
#local
#spring.data.mongodb.uri=mongodb+srv://swaminathan:swaminathan@test-padmasiniAdmin-1.jstwkng.mongodb.net/subjects?retryWrites=true&w=majority&appName=test-padmasiniAdmin-1

# Server config
#server.port=${PORT:8080}
server.port=${PORT:80}

# File upload config (50MB)
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB


# Active profile
spring.profiles.active=test

#Local-redis
#Spring Session Redis configuration
#spring.session.redis.flush-mode=on_save
#spring.session.redis.namespace=spring:session
#spring.session.store-type=redis
#
#
#spring.data.redis.host=127.0.0.1
#spring.data.redis.port=6379
#spring.data.redis.password=
#spring.data.redis.ssl.enabled=false

#Deploy-Redis
Spring Session Redis configuration
spring.session.redis.flush-mode=on_save
spring.session.redis.namespace=spring:session
spring.session.store-type=redis


server.servlet.session.cookie.same-site=none
server.servlet.session.cookie.secure=true
server.servlet.session.cookie.path=/
server.servlet.session.cookie.max-age=86400

# \u2705 AWS Configuration (NEW)
aws.region=ap-south-1
aws.bucket.name=trilokinnovations-test-admin
