spring.application.name=padmasiniAdmin_1
spring.data.mongodb.uri=mongodb+srv://swaminathan:swaminathan@test-padmasiniAdmin-1.jstwkng.mongodb.net/subjects?retryWrites=true&w=majority&appName=test-padmasiniAdmin-1
server.port=80
server.port=${PORT:80}
# Allow files up to 50MB
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB





